### ISSUE TITLE
Cold Sweat Insulation Bug

### ISSUE THREAD

**Issue by plmsw12** [LunaPixelStudios/SteamPunk#119]
### Describe the Bug

Cold Sweat Insulation not working, need to know if this is intentional or something isn't properly configured server side.

### Reproduction Steps

1. Apply insulating material to armor in sewing table
2. Turn on advanced tooltips, check item stats, insulation not appearing

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
report it to the cold sweat mod developers please

**Comment by ascaleon** [comment]
Sorry to reply to a closed issue, but for those who are still interested: this bug was caused by incompability with Legendary Tooltips and has been fixed in beta version ColdSweat-2.3-b01a. You could manually fix the problem by installing the newest version of ColdSweat until the modpack gets updated :)

**Comment by chorbintime** [comment]
thanks ^^
