### ISSUE TITLE
Server crash with modpack

### ISSUE THREAD

**Issue by ShulgaDmitriy** [LunaPixelStudios/SteamPunk#281]
### Describe the Bug

I'm trying to start my server with a modpack, but when I start I get a lot of crashes from different mods. On the client side AKA my computer, the build runs fine. But the server cannot start.

P.S This is my home server that is in my room. 4GB is allocated to the modpack from both my PC (Client) and the server. Build with 4GB of RAM works fine on my PC

### Reproduction Steps

1.Go to the server directory
2. Running server (./run.sh)
3.Waiting
4.Crash

### Screenshots and Videos

-

### Crash Report or Log

https://pastebin.com/tjXVL6FM

### Operating System

Ubuntu server 24.04 LTS   Kernel: 6.8.0-36-generic

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

Steampunk v24R

### Other Mods

-

**Comment by Henrique-DeSousa** [comment]
I think the crash is due to:
```
Mod §ejerintegration§r requires §6jeresources§r §o0.14.1.160 or above§r
§7Currently, §6jeresources§r§7 is §o§nnot installed,
```
at least I have that in my logs

**Comment by Henrique-DeSousa** [comment]
Actually, it might be due to another mod missing, spruceui that is required by RyoamicLights. However these are both imports of fabric mods, I haven't managed to get spruceui to be detected as its forge counterpart is called Obsidian, and renaming it won't solve it. The only way I've found is to make your modpack Ignore RyoamicLights which then makes it work

**Comment by ShulgaDmitriy** [comment]
> Единственный способ, который я нашел, это заставить ваш modpack игнорировать RyoamicLights, что затем заставит его работать

Thank you for your help! This actually made my modpack work.
