### ISSUE TITLE
Immersive Engineering Refinery UI graphics don't line up with current elements

### ISSUE THREAD

**Issue by zhs2** [LunaPixelStudios/SteamPunk#288]
### Describe the Bug

The old IE Refinery UI has three fluid displays and six bucket input/output slots, which the graphics were made for. The current UI has only bucket input/output for the resulting fluid and a catalyst slot, and said catalyst slot is not accounted for by the graphics nor does the second fluid display line up with it.

### Reproduction Steps

1. Build an Immersive Engineering Refinery
2. Open the UI
3. Hover mouse cursor over UI elements to see they do not line up with the graphics

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/1430430/836470eb-ef65-43b6-bc72-2faae4bdd59f)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by mycroftjr** [comment]
This is due to https://www.curseforge.com/minecraft/texture-packs/tetra_gui not properly backporting the fixes in https://www.curseforge.com/minecraft/texture-packs/tetra_gui/files/4392932 to https://www.curseforge.com/minecraft/texture-packs/tetra_gui/files/3933852, and there's sadly not much the pack can do about it.
Attached is the version I'm using, where I spliced the appropriate changes from 0.7.2 to 0.7.1.
[§b§lTetra_GUI_v.0.7.1.zip](https://github.com/user-attachments/files/16151952/b.lTetra_GUI_v.0.7.1.zip)

**Comment by SHXRKIEgg** [comment]
Will fix in next update
